name: homely_user
description: Homely

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  http: ^0.13.3
  shared_preferences: ^2.0.5
  connectivity_plus:
  jaguar_jwt: ^3.0.0
  flutter_local_notifications: ^9.0.0
  path_provider: ^2.0.2
  flutter_rating_bar: ^4.0.0  
  flutter_html: any
  sms_autofill: ^2.0.1
  intl:
  country_code_picker: ^2.0.1
  geolocator: ^9.0.2
  file_picker:
  shimmer:
  geocoding: 2.0.3
  google_maps_place_picker_mb: ^2.0.0-mb.16
  flutter_html_to_pdf: ^0.7.0
  permission_handler: 10.4.3
  curved_navigation_bar: ^1.0.1
  in_app_review: ^2.0.2
  carousel_slider: ^4.2.1
  open_filex:
  provider: ^6.0.0
  stripe_payment: ^1.1.4
  video_player: ^2.1.5
  flutter_svg:
  paytm: ^3.0.1
  share: ^2.0.4
  package_info: ^2.0.2
  url_launcher: ^6.0.3
  version: ^2.0.0
  flutter_downloader: 1.6.1
  speech_to_text: ^5.0.0
  tuple: ^2.0.0
  cached_network_image: ^3.1.0
  place_picker:
  google_maps_flutter: ^2.1.1
  webview_flutter: ^4.2.2
  youtube_player_flutter: ^8.1.2
  firebase_auth: ^4.4.1
  firebase_core: ^2.9.0
  firebase_messaging: ^14.4.0
  firebase_database: ^10.2.3
  firebase_dynamic_links: ^5.0.17
  flutter_polyline_points: ^1.0.0
#  phonepe_gateway:
  google_place: ^0.4.7
  fluttertoast: ^8.2.2
  photo_view: ^0.14.0
  razorpay_flutter: 1.3.0 #^1.3.5
  cc_avenue: ^1.0.3
  flutter_inappwebview: ^5.7.2+3
 # upgrader: 4.11.1
  google_sign_in:
  downloads_path_provider_28:
    path: ./downloads_path_provider

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_math_fork:
dependency_overrides:
  modal_bottom_sheet: ^3.0.0-pre
  file: ^6.1.4
  package_info_plus: ^4.2.0
  #geolocator: ^9.0.2
    # For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/
    - lib/Language/
    - assets/logo/


  fonts:
    - family: opensans
      fonts:
        - asset: assets/font/OpenSans-Regular.ttf
